import pytest
from finalproject.fasta_reader import FastaReader 

def test_fasta_reader(tmp_path): 
    
    fasta_file = tmp_path / "test.fasta"
    
    fasta_file.write_text(
        ">seq1\n"
        "GTCCAAAAATTGGGGGGAGTAGATTGACCGTTCAGGGTCTCATATTTCGTGGTGCCGACA\n"
        ">seq1_var1\n"
        "GTCCAAATATTGGGGAGAGTAGATTGATCGTTCAGGGTCTCATATTTCGGTGCCGACA\n"
        
        ">seq2\n"
        "TAGCTGCTAGTCACATTATATAACTGTTATCGCAAAAACGTGTACATTTGCACAGAGATA\n"
        ">seq2_var1\n"
        "TCCGCTTCCCATTATATAACTGTTATCGCAAAAACGTGTACACTTGCACAGAGATA\n"
        
        ">seq3\n"
        "GGGGTTGAGTTGTTGGCTCGCTCCTAGCATATTCGCACATTTGATCGGAGTGAACACAAT\n"
        ">seq3_var1\n"
        "GGGTTGAGGTGTTGGCTCGCCTAGCATATTCGCACATTAGATCGGAGTGAACACAAC\n"
        
        ">seq4\n"
        "GATGTATTGCGATTCCGGTCTTTCTTTGATGGCCCTGGCCAAGGTTACAGGTATACAGCA\n"
        ">seq4_var1\n"
        "GATGCATTGCGATTCGGTCTTTCTTTGATGTCCCTGGCCAAGGTTACAGGGTATAGCA\n"

        ">seq5\n"
        "CCCTTACTTTGAGCAGCTAGGTGGACTGTCGGATTTGTGCATGCAGCCTCCTGTATTCAG\n"
        ">seq5_var1\n"
        "CCCTAACTTTGCGCAGCTAGGTGGACTGTCGGTTTGTACATACAGCCTCCTGTATTCAG\n"
    )
        
    reader = FastaReader(fasta_file)
    sequences = reader.read()

    assert sequences["seq1"][0] == "GTCCAAAAATTGGGGGGAGTAGATTGACCGTTCAGGGTCTCATATTTCGTGGTGCCGACA"
    assert sequences["seq1"][1] == "GTCCAAATATTGGGGAGAGTAGATTGATCGTTCAGGGTCTCATATTTCGGTGCCGACA"
    
    assert sequences["seq2"][0] == "TAGCTGCTAGTCACATTATATAACTGTTATCGCAAAAACGTGTACATTTGCACAGAGATA"
    assert sequences["seq2"][1] == "TCCGCTTCCCATTATATAACTGTTATCGCAAAAACGTGTACACTTGCACAGAGATA"
    
    assert sequences["seq3"][0] == "GGGGTTGAGTTGTTGGCTCGCTCCTAGCATATTCGCACATTTGATCGGAGTGAACACAAT"
    assert sequences["seq3"][1] == "GGGTTGAGGTGTTGGCTCGCCTAGCATATTCGCACATTAGATCGGAGTGAACACAAC"
    
    assert sequences["seq4"][0] == "GATGTATTGCGATTCCGGTCTTTCTTTGATGGCCCTGGCCAAGGTTACAGGTATACAGCA"
    assert sequences["seq4"][1] == "GATGCATTGCGATTCGGTCTTTCTTTGATGTCCCTGGCCAAGGTTACAGGGTATAGCA"
    
    assert sequences["seq5"][0] == "CCCTTACTTTGAGCAGCTAGGTGGACTGTCGGATTTGTGCATGCAGCCTCCTGTATTCAG"
    assert sequences["seq5"][1] == "CCCTAACTTTGCGCAGCTAGGTGGACTGTCGGTTTGTACATACAGCCTCCTGTATTCAG"

def test_fasta_reader_on_two_line(tmp_path):
    
    fasta_file = tmp_path / "test.fasta"
    fasta_file.write_text(
        ">seq1\n"
        "GTCCAAAAATTGGGGGGAGTAGATTGACCGTTCAGGG\n"
        "TCTCATATTTCGTGGTGCCGACA\n"
        ">seq1_var1\n"
        "GTCCAAATATTGGGGAGAGT\n"
        "AGATTGATCGTTCAGGGTC\n"
        "TCATATTTCGGTGCCGACA\n"
    )

    reader = FastaReader(fasta_file)
    sequences = reader.read()

    assert sequences["seq1"][0] == "GTCCAAAAATTGGGGGGAGTAGATTGACCGTTCAGGGTCTCATATTTCGTGGTGCCGACA"
    assert sequences["seq1"][1] == "GTCCAAATATTGGGGAGAGTAGATTGATCGTTCAGGGTCTCATATTTCGGTGCCGACA"

